### ISSUE TITLE
Error 1015,You are being rate limited

### ISSUE THREAD

**Issue by cb123321** [oliverjrose99/Recordurbate#15]
Hello :)
I have used this great product for over one year, but starting yesterday morning CB gives me a error as soon as I start the script ( both v1 and v2)

The message on their homepage are "Error 1015 You are being rate limited". (This ban expires after a few minutes.)

Can someone help me to get a waiting period somewhere, so my requests to broadcasters rooms not are so quick? May that help?

The timestamp from this new log in v2 looks like down below, after they ban me,, There is just a few ms between each try to acces a room? 

2019-10-12 07:46:04,192 - Successfully started daemon, pid: 3009
2019-10-12 07:46:09,748 - Expecting value: line 1 column 1 (char 0)
2019-10-12 07:46:10,088 - Expecting value: line 1 column 1 (char 0)
2019-10-12 07:46:10,138 - Expecting value: line 1 column 1 (char 0)
2019-10-12 07:46:10,184 - Expecting value: line 1 column 1 (char 0)
2019-10-12 07:46:10,229 - Expecting value: line 1 column 1 (char 0)

**Comment by oliverjrose99** [comment]
How many people are you trying to record? i'll try and add a delay option to see if it helps.

**Comment by oliverjrose99** [comment]
i've added a rate limit option. please clone the repo and check if it helps. (not currently on a release version)

**Comment by cb123321** [comment]
Hello, so far it seems to work well, i'll play with rate limit time later. Thanks alot, you are a king :)

**Comment by cb123321** [comment]
I have a problem with the new daemon. 
Problems seems to be that daemon quitting after last broadcaster in the list are checked? Pid-file and process disappear without any new info in the log. Started recordings keeps recording. When I start daemon again, a second recording begins.  Do you have any solution for me? Thanks :)

**Comment by oliverjrose99** [comment]
do you have the rate_limit and rate_limit_time options in the config file? currenly it will crash without them in the config.

**Comment by cb123321** [comment]
Yes, right now it's:
    "rate_limit": true,
    "rate_limit_time": 3,

**Comment by oliverjrose99** [comment]
Thanks for helping with the issue. ive pushed a change to log errors in the main loop if you wanna clone the repo again.

**Comment by cb123321** [comment]
Ok, here are some, not so useful, info..
This time the process keep alive for about exatly 1 hour and I have no error in the log :(
Can we add logging to more part of the script? :)
You can't repoduce my problem?

**Comment by oliverjrose99** [comment]
i cant seem to reproduce the error. ive wraped the entier loop in a try catch which should log any errors which occur if you wanna clone the repo.

**Comment by cb123321** [comment]
Thanks, I give it a try right now :)

**Comment by cb123321** [comment]
Script still running, but i got this so far

2019-10-14 18:51:14,640 - Starting daemon
2019-10-14 18:51:14,642 - Successfully started daemon, pid: 10673
**[Edit: 1 model stopped recording 19.08]**
2019-10-14 19:08:58,068 - loop error
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/xxxx/CB/rectest/Recordurbate-master/recordurbate/bot.py", line 99, in run
    self.logger.info("Stopped recording", rec[0])
  File "/usr/lib/python3.6/logging/__init__.py", line 1308, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1072, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1000, in emit
    self.handleError(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 917, in handleError
    sys.stderr.write('--- Logging error ---\n')
ValueError: I/O operation on closed file.
2019-10-14 19:08:59,083 - loop error
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

**Comment by oliverjrose99** [comment]
im an idiot, the params weren't right, repos been updated

**Comment by cb123321** [comment]
Now it seems to work :D 
Thanks dude !

**Comment by oliverjrose99** [comment]
perfect, ill make it into a release, open another issue if you find any other issues.
