### ISSUE TITLE
Loop error

### ISSUE THREAD

**Issue by cb123321** [oliverjrose99/Recordurbate#19]
Hello,
I get a loop error when deleting, can you help me? :) 

2019-11-02 11:08:20,258 - loop error
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/CB/rectest/Recordurbate-master/recordurbate/bot.py", line 92, in run
    self.reload_config()
  File "/CB/rectest/Recordurbate-master/recordurbate/bot.py", line 52, in reload_config
    self.logger.info(streamer[0], "has been removed")
  File "/usr/lib/python3.6/logging/__init__.py", line 1308, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1072, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1000, in emit
    self.handleError(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 917, in handleError
    sys.stderr.write('--- Logging error ---\n')
ValueError: I/O operation on closed file.

**Comment by oliverjrose99** [comment]
Make sure your on the lastest version and let me know if it still happens.

**Comment by cb123321** [comment]
I have the latest and still problem when i delete a broadcaster

**Comment by oliverjrose99** [comment]
can you put what command you are running.

**Comment by oliverjrose99** [comment]
doesn't matter, ive found the issue, will push a fix soon, sorry

**Comment by oliverjrose99** [comment]
@cb123321 I've made an update, change your version and let me know

**Comment by cb123321** [comment]
It works good now, thanks alot :)
