### ISSUE TITLE
Error seen in the logs

### ISSUE THREAD

**Issue by vold4545** [oliverjrose99/Recordurbate#30]
2019-12-19 02:31:00,737 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/pi/programs/recorder/recordurbate/bot.py", line 75, in is_online
    if r.json()["room_status"] == "public":
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vold4545** [comment]
Moreover, I see multiple files in mp4.part format and they do not open properly. This is happening while the stream is finished. Is there any solution for that?

**Comment by oliverjrose99** [comment]
weird, this may have been a chaturbate issue if the query didnt respond with valid JSON. The part files are stream segments and indicate that youtube-dl or ffmpeg didnt close properly. Please keep trying to record the streams and report if you experience the error again..

**Comment by vold4545** [comment]
sure. Is there anyway to repair a part file, so we can play it with vlc?

**Comment by oliverjrose99** [comment]
I believe you can rename a part file to just .mp4 and vlc might play it even if its only 5 seconds long. Im not sure what command or prog you would need to add it to the end of the larger/complete stream file.

**Comment by virtadpt** [comment]
You could use ffmpeg to splice the files together:
* Rename the files so that there are no spaces in the filenames: file_1.mp4, file_2.mp4, etc.
* Create a file `concat.txt` that contains the filenames, and looks like this:
```
file 'file_1.mp4'
file 'file_2.mp4'
...
```
* `ffmpeg -f concat -i concat.txt -c copy output.mp4`

**Comment by vold4545** [comment]
Thanks, but I got this error:

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1aba2c0] moov atom not found
[concat @ 0x1ab11c0] Impossible to open 'a.mp4'
concat.txt: Invalid data found when processing input

**Comment by cb123321** [comment]
Hello Oliver,
I get this message every time CB has website problems.
Can you fix the output message in the log file to write just "Expecting value: line 1 column 1 (char 0)"?

 Thanks :)

2020-01-02 11:58:36,816 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/media/CB/rectest/Recordurbate-master/recordurbate/bot.py", line 75, in is_online
    if r.json()["room_status"] == "public":
  File "/home/jonas/.local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DerBunteBall** [comment]
I have the same error in my log.

Just give it a nice description like "API gave wrong JSON" and retry after 15 seconds or so.

In my case it appeared in two situations:

1. Simply randomly which seems to be a website problem (cb123321 already mentioned)
2. When a room gets crazy. One of the girls I record seems to had technical problems this evening. The log shows her room switching from on to off and otherwise within times from 23 seconds up to 3 minutes. Eventually the API fails to give back valid JSON in this cases when the room state is a bit unclear.

Should be debugged further but something like crashed youtube-dl sessions I have not seen until now.

Best Regards

PS: Soory for my bad english

**Comment by djdmg** [comment]
Hello @oliverjrose99,

First, thanks for this bot.
About this isssue with JSON i saw that is become when we had too much models in config file. 
With they do too much requests and the response from the server was bad.
I fix it by simple way by add a timer between each request in bot.py:

try:
            time.sleep(3)
            r = requests.post(url, headers=headers, data=data)

I tried with the value of 1 or 2 seconds but it was too low.

I hope it will help
Regards
