### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by mccande** [oliverjrose99/Recordurbate#38]
Hello

Today I have this error appearing in rb.log.  The application seems to be working fine and the only problem is that rb.log is filling up with these messages so I cannot see the nice log of what is being recorded.

Is there some obvious explanation?

2020-02-13 08:23:58,922 - Successfully started daemon, pid: 10088
2020-02-13 08:26:14,657 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/mccande/recordurbate/bot.py", line 75, in is_online
    if r.json()["room_status"] == "public":
  File "/home/mccande/.local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-02-13 08:26:16,732 - Expecting value: line 1 column 1 (char 0)

**Comment by oliverjrose99** [comment]
i wanna say this is an issue with cb it's self, ive seen this before in other issues, it should fix its self. tbh the way ive done it is bad, the script assumes the requrest will alway return valid JSON

**Comment by mccande** [comment]
Thanks.  The program seems to be working fine though I don't know if these errors mean that some streams which should record are not.

Anyway thanks again
