### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by PurpleConcealment** [oliverjrose99/Recordurbate#43]
Hi !
I have used Recordurbate for a few months. Lately (last few weeks), I have been unable to download more than a few short videos, now it crashes pretty much as soon as it tries staring recording. I have made sure youtube-dl is up to date. I run it on a Xubuntu virtual machine and a WSL Ubuntu. I currently only have one streamer on the list, and use the rate limiter with a 60 seconds period. I have a stable internet connection.

Here are the logs :
```
2020-05-02 22:40:00,292 - Starting daemon
2020-05-02 22:40:00,305 - Successfully started daemon, pid: 93
2020-05-02 22:40:01,007 - Started to record jul_la_la
2020-05-02 22:42:01,055 - Stopped recording jul_la_la
2020-05-02 22:42:40,067 - HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f24097a1dd8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f24097a1dd8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f24097a1dd8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/louis/recordurbate/bot.py", line 74, in is_online
    r = requests.post(url, headers=headers, data=data)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f24097a1dd8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2020-05-02 22:44:45,506 - Started to record jul_la_la
```

**Comment by oliverjrose99** [comment]
looks like an issue with dns and/or nameservers, check your settings for what they are, if you can ping other domains, etc

**Comment by PurpleConcealment** [comment]
You're correct. Pinging google results in the same "Temporary failure in name resolution error". I'll look into that. Weird that Recordurbate is still able to see which streamers are online though. Thank you !
