### ISSUE TITLE
How to use proxy?

### ISSUE THREAD

**Issue by TeslaLyon** [oliverjrose99/Recordurbate#47]
How to use proxy?

**Comment by oliverjrose99** [comment]
There are options within youtube-dl to use a proxy, the requests which are made within the script dont have options for proxy use. Best bet is probably to configure whatever distro your using to use a proxy.

**Comment by TeslaLyon** [comment]
Okay, thanks for the reply, I found this in the log：

2020-07-28 19:01:52,321 - Starting daemon
2020-07-28 19:01:52,328 - Successfully started daemon, pid: 21951
2020-07-28 19:01:56,239 - Started to record gulure
2020-07-28 19:02:22,290 - Started to record lillemax
2020-07-28 19:18:56,924 - Stopped recording lillemax
2020-07-28 19:19:18,374 - Started to record lillemax
2020-07-28 19:27:03,989 - HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 930, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liangshuo/code/py-project/Recordurbate/recordurbate/bot.py", line 79, in is_online
    r = requests.post(url, headers=headers, data=data, proxies=proxy_ip)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
2020-07-28 19:37:26,946 - HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 930, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liangshuo/code/py-project/Recordurbate/recordurbate/bot.py", line 79, in is_online
    r = requests.post(url, headers=headers, data=data, proxies=proxy_ip)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
2020-07-28 19:59:11,176 - Caught stop signal, stopping
2020-07-29 00:11:41,752 - Successfully stopped

**Comment by oliverjrose99** [comment]
> HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

Check that your proxy works, e.g. can get request google and chaturbate
