### ISSUE TITLE
It doesn't look to work anymore :(

### ISSUE THREAD

**Issue by Mamur16** [oliverjrose99/Recordurbate#5]
I think it maybe because youtube-dl but not sure.
I ran the same command that the proccess usually use and added verbose
```
root@mamuburns2:~# python3 /usr/local/bin/youtube-dl https://chaturbate.com/dream_grouphot/ --config-location /opt/recordurbate/configs/youtube-dl.config
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-o', 'videos/%(id)s/%(title)s.%(ext)s', '--verbose']
[debug] Command-line args: ['https://chaturbate.com/dream_grouphot/', '--config-location', '/opt/recordurbate/configs/youtube-dl.config']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-7-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[Chaturbate] dream_grouphot: Downloading webpage
[Chaturbate] dream_grouphot: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/chaturbate.py", line 68, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1286, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by oliverjrose99** [comment]
does this occur with other streamers as well. ive just tried the lastest version of youtube-dl and ffmepg on windows and it seems to work fine.

**Comment by oliverjrose99** [comment]
If it was a private show, ticket show, etc then it wont work as it relies on the public stream url,  apart from that my testing worked, create a new issue if it happens again, but with more info.
