### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by weigeloveu** [oliverjrose99/Recordurbate#58]
```
ModuleNotFoundError: No module named 'requests'
~/Recordurbate/recordurbate $ python Recordurbate.py help
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Recordurbate/recordurbate/Recordurbate.py", line 3, in <module>
    from daemon import Daemon
  File "/data/data/com.termux/files/home/Recordurbate/recordurbate/daemon.py", line 12, in <module>
    from bot import Bot
  File "/data/data/com.termux/files/home/Recordurbate/recordurbate/bot.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
~/Recordurbate/recordurbate $ pip install reuqests
ERROR: Could not find a version that satisfies the requirement reuqests (from versions: none)
ERROR: No matching distribution found for reuqests
~/Recordurbate/recordurbate $
```

**Comment by jasonbronson** [comment]
@weigeloveu you spelled requests wrong on the pip install line.

**Comment by Dethkiller15** [comment]
Got the same error myself. Fresh install and made sure to install everything required in a ubuntu docker image and still cant do anything.

**Comment by Dethkiller15** [comment]
Found a solution for it actually you need to install the python requests ether via "pip3 install requests" for python3 or "apt-get install python-requests"

Found the solution here https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

**Comment by leet86** [comment]
Is this resolved?
