### ISSUE TITLE
HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ 

### ISSUE THREAD

**Issue by jeffkerby** [oliverjrose99/Recordurbate#63]
I am seeing the following errors for the last couple of days after not having any successful recordings. Then it keeps repeating, how can I resolve this error or troubleshoot?

2021-12-26 01:01:13,249 - Starting daemon
2021-12-26 01:01:13,254 - Successfully started daemon, pid: 2332
2021-12-26 01:01:25,730 - Started to record arianaonfire
2021-12-26 01:02:44,709 - HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa975da4e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 144, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 298, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 153, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa975da4e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa975da4e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/recordurbate/bot.py", line 74, in is_online
    r = requests.post(url, headers=headers, data=data)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /get_edge_hls_url_ajax/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa975da4e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2021-12-26 01:02:48,998 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/root/recordurbate/bot.py", line 75, in is_online
    if r.json()["room_status"] == "public":
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-12-26 01:02:49,087 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/root/recordurbate/bot.py", line 75, in is_online
    if r.json()["room_status"] == "public":
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by oliverjrose99** [comment]
it cant resolve the domain name, check your connection settings.

**Comment by jeffkerby** [comment]
@oliverjrose99 it seems to be only the chaturbate domain all other domains ping OK. Can I adjust anything in the config file?
