### ISSUE TITLE
Files stopped showing up

### ISSUE THREAD

**Issue by smacknuts** [oliverjrose99/Recordurbate#92]
Any idea why the video files would stop showing up?  The folder for the model is created but no video file is being written in those folders.  I am assuming this is a function of YouTube-dl.  Any chance anyone knows how to fix this?

**Comment by divenxx** [comment]
can you share the log?

**Comment by smacknuts** [comment]
To be honest the log looks fine.  There is an error in there that occurs every once in a while which forces me to restart recordurbate, but that is fairly normal.

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/wightman/recordurbate/bot.py", line 74, in is_online
>     r = requests.post(url, headers=headers, data=data)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> 2023-03-31 00:24:57,631 - Stopped recording model
> 2023-03-31 00:30:46,877 - Started to record model
> 2023-03-31 00:33:32,386 - Stopped recording model
> 2023-03-31 10:37:08,288 - Starting daemon
> 2023-03-31 10:37:08,292 - Successfully started daemon, pid: 43941

**Comment by divenxx** [comment]
other possibility is that only one model get recorded and other are ignored

**Comment by smacknuts** [comment]
My guess is that YouTube-dl isnt working properly.  Does it have to be 2019.11.22, or can it be the latest version?

**Comment by divenxx** [comment]
that is easy to test then, in two terminal window, call youtube-dl with two diffrent streams, if they both work it means that the problem is not there

**Comment by Acenl12** [comment]
I noticed they also implemented Cloudflare, not sure if youtube-dl can handle the protection cloudflare offers.

**Comment by Telly-bit** [comment]
I'm wondering if this is still working?

I just installed it, but unfortunately it doesn't generate any files in the video folder. I used to work with the steamlink version which is still working on my old pc. Now with the youtube-dl I just can't get it to work..
