### ISSUE TITLE
loop error in rb.log

### ISSUE THREAD

**Issue by Acenl12** [oliverjrose99/Recordurbate#94]
```
bot.py:132 - run()]- Started to record ****
[**** bot.py:155 - run()]- loop error
Traceback (most recent call last):
  File "/***/Recordurbate/recordurbate/bot.py", line 138, in run
    self.processes.append([streamer[0], subprocess.Popen(args, 0)])
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'youtube-dl'
```

OS version:
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Please help for a fix!

**Comment by divenxx** [comment]
seems that the youtube-dl version you have was not made for the distro you are using, how did you install it?

**Comment by Acenl12** [comment]
Using pip3 as documented                                                                                                                                                                
 ```
youtube-dl --version
2021.12.17
```

```
pip3 show youtube-dl
Name: youtube-dl
Version: 2021.12.17
Summary: YouTube video downloader
Home-page: https://github.com/ytdl-org/youtube-dl
Author: Ricardo Garcia
Author-email: ytdl@yt-dl.org
License: Unlicense
Location: /usr/local/lib/python3.11/dist-packages/youtube_dl-2021.12.17-py3.11.egg
Requires:
Required-by:
```

**Comment by Acenl12** [comment]
I'm also getting this error now: `ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)`

**Comment by divenxx** [comment]
i have had enough issues with youtube-dl, it is no longer maintained i already migarted to a maintaned fork called https://github.com/yt-dlp/yt-dlp
i recommend switching to that one too

**Comment by Acenl12** [comment]
Thanks, to fix the HTTP error 403 I had to setup a VPN, because something was blocking the traffic to CB.

**Comment by Acenl12** [comment]
> i have had enough issues with youtube-dl, it is no longer maintained i already migarted to a maintaned fork called https://github.com/yt-dlp/yt-dlp i recommend switching to that one too

I switched to yt-dlp, only had to update the config.json al default YouTube-dl options in the config work also with yt-dlp. So i created a pull request
